function init_sync(url::String)
    current_path = pwd()
    cd(filedir)
    run(`$(git()) init`)
    run(`$(git()) checkout -b main`)
    run(`$(git()) remote add origin $url`)
    run(`$(git()) add .`)
    run(`$(git()) commit -m "initial sync commit"`)
    run(`$(git()) push -u origin main`)
    cd(current_path)
end

function sync_changes(;note="update files.")
    current_path = pwd()
    cd(filedir)
    run(`$(git()) add .`)
    run(`$(git()) commit -a -m "Balance_jl Auto Sync: $note"`)
    run(`$(git()) pull`)
    run(`$(git()) push`)
    cd(current_path)
end
